import { auth } from "@/server/auth"
import { redirect } from "next/navigation";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();
  if (session) return redirect("/")
  return (
    <>{children}</>
  )
}
